version: "3"
services:
  nginx:
    image: nginx:1.18
    container_name: autoindex
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - /srv/autoindex/default.conf:/etc/nginx/conf.d/default.conf
      - /srv/autoindex/data:/srv/data