version: "3"
services:
  nginx:
    image: nginx:1.18
    container_name: autoindex
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./passwd.txt:/etc/nginx/passwd.txt
      - ./data:/srv/data